### PR TITLE
[ISSUE-62]: Fix closing li tag, fix nested list

### PR DESCRIPTION
**Pull request by FJCrux**
There is fix for https://github.com/evbacher/gd2md-html/issues/62
You can find google doc with fixed addon version here https://docs.google.com/document/d/1VnPTSkm2AxzR2Up0tBXjRx5vvktaOwgKxLB2tALREh0/edit?usp=sharing

### CODE REVIEW

**Comment by evbacher** [comment]
Thanks for attacking the list bugs! 

Your fix seems to work on your test file, but it breaks other list cases. Can you test it out on the dev verification file as described here: https://github.com/evbacher/gd2md-html/blob/master/dev.md#modifying-docs-to-markdown-code

Also, let me know if you have any suggestions for simplifying this process. This is my first real open-source project.

**Comment by FJCrux** [comment]
I checked the test files, but I had doubts whether there were problems there:
1. In case `Lists with code blocks`, first element must include code block, but code block is not a part list item
2. In part `$ cat file | grep dog | wc` html look like wrong even in master branch(

If you meant other cases, please write which ones.

**Comment by evbacher** [comment]
I'll try to get time to take another look at this.

But you'll also need to sign the CLA referred to in [CONTRIBUTING.md](https://github.com/evbacher/gd2md-html/blob/master/CONTRIBUTING.md). I cannot accept code into this repo without that agreement.

**Comment by FJCrux** [comment]
I sign the CLA

**Comment by bravetheheat** [comment]
@evbacher is there anything I can do to help get this merged?

**Comment by pencerw** [comment]
☝️ ditto! would love this bug fix and am happy to chip in to get it done

**Comment by evbacher** [comment]
It breaks other test cases, so I am not going to merge. I'll check again and let you know which cases it breaks.

**Pull request closed without merging**
